// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseLocalMSIX() {
  return window['go']['main']['App']['ChooseLocalMSIX']();
}

export function DownloadLatest() {
  return window['go']['main']['App']['DownloadLatest']();
}

export function DryRunLocal(arg1) {
  return window['go']['main']['App']['DryRunLocal'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ProbeLatest() {
  return window['go']['main']['App']['ProbeLatest']();
}
