// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseLocalMSIX():Promise<main.PackageInfo>;

export function DownloadLatest():Promise<main.DownloadResult>;

export function DryRunLocal(arg1:string):Promise<main.DownloadResult>;

export function GetStatus():Promise<main.AppStatus>;

export function ProbeLatest():Promise<main.ProbeResult>;
